/**
 * Тексты сайта на трёх языках.
 *
 * Один файл на все страницы: строка «Оплатить» встречается в шапке, на первом
 * экране, в тарифах и в кабинете, и переводить её четырежды — значит однажды
 * перевести по-разному.
 *
 * Ключи одинаковые во всех трёх словарях. Пропуск не рушит страницу: i18n.js
 * возьмёт английскую строку, а если нет и её — покажет сам ключ, и дырка будет
 * видна сразу, а не притворится пустым местом.
 *
 * `{имя}` внутри строки — подстановка: цена, процент, год, название почты.
 *
 * Правовых документов здесь нет: договор должен читаться и без JavaScript,
 * поэтому у него отдельный файл на каждый язык (terms.html, terms-uk.html,
 * terms-en.html и так далее).
 */

export const STRINGS = {

  /* ============================== русский ============================== */

  ru: {
    'common.langLabel': 'Язык сайта',
    'common.download': 'Скачать',
    'common.pay': 'Оплатить',
    'common.back': 'На главную',
    'common.home': 'Главная',
    'common.footAccount': 'Личный кабинет',
    'common.footTerms': 'Условия использования',
    'common.footPrivacy': 'Конфиденциальность',
    'common.footRefund': 'Возврат средств',
    'common.copy': '© {year} AutoSwipe AI · не связаны с Tinder и Match Group',

    'index.title': 'AutoSwipe AI — расширение Chrome для Tinder',
    'index.desc': 'Расширение Chrome, которое само листает рекомендации Tinder по вашим условиям: возраст, рост, расстояние, стоп-слова в описании и оценка фотографий моделью.',
    'index.navHow': 'Как работает',
    'index.navWhat': 'Возможности',
    'index.navPrice': 'Цена',
    'index.navFaq': 'Вопросы',

    'index.heroEyebrow': 'Расширение для браузера Chrome',
    'index.heroTitle': 'Tinder листает<br>себя сам',
    'index.heroLead': 'Вы один раз задаёте условия — возраст, рост, расстояние, стоп-слова. Дальше расширение само открывает анкеты, оценивает фотографии и ставит Like или Nope.',
    'index.btnDownloadFull': 'Скачать расширение',
    'index.btnPayFull': 'Оплатить подписку',
    'index.heroNote': 'Бесплатно · Chrome 116 и новее · установка в один клик',
    'index.soon': 'Скоро в Chrome Web Store',
    'index.soonNote': 'Расширение проходит проверку в Chrome Web Store. Кабинет и оплата уже работают.',

    'index.mockScore': 'Оценка модели 8,4 / 10',
    'index.mockName': 'Анна, 26',
    'index.mockMeta': '168 см · 4 км от вас · 5 фото',
    'index.mockAge': 'Возраст',
    'index.mockHeight': 'Рост',
    'index.mockHeightVal': '160 – 180 см',
    'index.mockDistance': 'Расстояние',
    'index.mockDistanceVal': 'до 15 км',
    'index.mockLooks': 'Внешность',
    'index.mockStart': 'Старт',
    'index.mockLog': '<i class="y">♥</i> Like — оценка 8,4<br><i class="n">✕</i> Nope — стоп-слово «сети»<br><i class="y">♥</i> Like — оценка 7,1<br><i class="n">✕</i> Nope — 42 км, далеко',

    'index.howTitle': 'Три шага — и дальше само',
    'index.howSub': 'Ничего настраивать в браузере не нужно: панель открывается прямо поверх Tinder.',
    'index.step1Title': 'Установите',
    'index.step1Text': 'Нажмите «Скачать расширение» и подтвердите установку в Chrome. Занимает полминуты.',
    'index.step2Title': 'Задайте условия',
    'index.step2Text': 'Возраст, рост, расстояние, минимум фотографий, стоп-слова в описании. Ползунки и галочки, писать ничего не нужно.',
    'index.step3Title': 'Нажмите «Старт»',
    'index.step3Text': 'Расширение листает ленту само. Кто подошёл и почему — видно в логе панели, счётчики свайпов рядом.',

    'index.whatTitle': 'Что входит',
    'index.whatSub': 'Фильтры по анкете работают сразу и бесплатно. Оценка по фотографиям открывается подпиской.',
    'index.freeTitle': 'Бесплатно, сразу после установки',
    'index.free1': 'Возраст, рост, расстояние',
    'index.free2': 'Минимум фотографий в анкете',
    'index.free3': 'Стоп-слова в описании, в том числе регулярные выражения',
    'index.free4': 'Только с отметкой Verified или недавно активные',
    'index.free5': 'Лимит свайпов за сессию и доля отказов',
    'index.free6': 'Интерфейс на русском, українською и English',
    'index.proTitle': 'По подписке <span class="badge">AI</span>',
    'index.pro1': '<b>Фильтр по внешности</b> — оценка модели от 1 до 10 и отбор по диапазону',
    'index.pro2': '<b>Фильтр по телосложению</b> — рост и вес по фотографиям, диапазон ИМТ',
    'index.pro3': 'Отбор по тому, что видно на снимке, а не только по заполненным полям анкеты',

    'index.priceTitle': 'Цена',
    'index.priceSub': 'Оплата криптовалютой или картой с конвертацией. Автопродления нет — вы платите за выбранный срок, и он не спишется сам.',
    'index.planMonth': 'Месяц',
    'index.planMonthPer': 'за 1 месяц доступа',
    'index.planMonthBtn': 'Оплатить месяц',
    'index.planYear': 'Год',
    'index.planYearPer': 'за 12 месяцев доступа',
    'index.planYearBtn': 'Оплатить год',
    'index.ribbon': 'Выгоднее',
    'index.save': 'экономия {n}%',
    'index.priceFoot': 'Оплата открывается в кабинете: нужен аккаунт — тот же, с которым вы входите в расширении.<br><a data-i18n-doc="refund" href="/refund.html">Условия возврата</a>',

    'index.faqTitle': 'Частые вопросы',
    'index.faqSub': 'Коротко о том, что спрашивают до покупки.',
    'index.q1': 'Нужен ли аккаунт?',
    'index.a1': 'Да. Расширение работает под аккаунтом — он же связывает вас с подпиской. Регистрация по почте и паролю, прямо в окне расширения или здесь на сайте.',
    'index.q2': 'Куда уходят мои фотографии и переписки?',
    'index.a2': 'Переписки не читаются вовсе. Фотографии профилей из ленты отправляются во внешнюю модель для оценки телосложения и внешности — без этого фильтры по снимкам работать не могут. Ваши собственные данные Tinder никуда не передаются.',
    'index.q3': 'Насколько точна оценка по фотографии?',
    'index.a3': 'Это прикидка. Ракурс, одежда и обработка сдвигают её, а оценка внешности вдобавок отражает предвзятость данных, на которых модель обучалась. Число будет стабильным, но считать его объективным не стоит.',
    'index.q4': 'Как устроена оплата и можно ли отменить?',
    'index.a4': 'Вы покупаете доступ на срок: месяц или год. Автосписания нет — с криптовалютой его технически не существует, поэтому отменять нечего. Не продлили — доступ просто закончился в оплаченную дату. Продлили раньше срока — новый период прибавится к остатку, ничего не сгорает.',
    'index.q5': 'Это разрешено правилами Tinder?',
    'index.a5': 'Нет. Правила Tinder запрещают автоматизацию действий в приложении, и аккаунт за это могут ограничить или заблокировать. Расширение делает паузы между свайпами и держит долю отказов, чтобы поведение не выглядело машинным, но гарантий это не даёт. Решение и риск — ваши.',

    'index.bandTitle': 'Готовы попробовать?',
    'index.bandSub': 'Установка бесплатна. Подписка нужна только для оценки по фотографиям.',

    'account.title': 'AutoSwipe AI — подписка',
    'account.payTitle': 'Оплата подписки',
    'account.payText': 'Открываю форму оплаты…',
    'account.backToTinder': 'Вернуться в Tinder',
    'account.flow1': '1. Вход',
    'account.flow2': '2. Оплата',
    'account.signInTitle': 'Вход в аккаунт',
    'account.signUpTitle': 'Регистрация',
    'account.tabIn': 'Вход',
    'account.tabUp': 'Регистрация',
    'account.leadIn': 'Та же почта и пароль, что и в расширении.',
    'account.leadUp': 'Этой же почтой и паролем вы будете входить в расширении.',
    'account.email': 'Почта',
    'account.password': 'Пароль',
    'account.password2': 'Пароль ещё раз',
    'account.submitIn': 'Войти',
    'account.submitUp': 'Зарегистрироваться',
    'account.resend': 'Отправить письмо ещё раз',
    'account.openMail': 'Открыть {name}',
    'account.subTitle': 'Подписка',
    'account.rowAccount': 'Аккаунт',
    'account.rowStatus': 'Состояние',
    'account.rowUntil': 'Оплачена до',
    'account.pickTitle': 'Выберите срок',
    'account.pickHint': 'Нажмите — откроется форма оплаты.',
    'account.payMonth': 'Оплатить месяц — {price}',
    'account.payYear': 'Оплатить год — {price}',
    'account.saveYear': 'годовая выгоднее на {n}%',
    'account.payNote': 'Криптовалютой или картой с конвертацией. Автосписания нет — срок продлеваете сами, новый период прибавляется к оплаченному.',
    'account.signOut': 'Выйти',
    'account.whatTitle': 'Что открывает подписка',
    'account.what1': '<b>Фильтр по внешности</b> — отбор по оценке модели 1–10, а не по анкетным полям.',
    'account.what2': '<b>Фильтр по телосложению</b> — диапазон ИМТ по фотографиям.',
    'account.what3': 'Остальные фильтры — возраст, рост, расстояние, стоп-слова — работают без подписки.',
    'account.linkTerms': 'Условия',
    'account.linkRefund': 'Возврат',
    'account.linkPrivacy': 'Конфиденциальность',

    'account.stActive': 'активна',
    'account.stTrialing': 'пробный период',
    'account.stPastDue': 'платёж не прошёл',
    'account.stPaused': 'приостановлена',
    'account.stCanceled': 'отменена',
    'account.stNone': 'нет',

    'account.errEmpty': 'Введите почту и пароль',
    'account.errInvalid': 'Неверная почта или пароль',
    'account.errNotConfirmed': 'Почта не подтверждена — перейдите по ссылке из письма',
    'account.errWeak': 'Пароль короче 6 символов',
    'account.errExists': 'Такая почта уже зарегистрирована',
    'account.errValidation': 'Проверьте введённые данные',
    'account.errRate': 'Слишком часто — подождите минуту',
    'account.errMismatch': 'Пароли не совпадают',
    'account.errSimple': 'Пароль слишком простой — его подберут',
    'account.errTaken': 'Такая почта уже зарегистрирована — войдите или восстановите пароль',
    'account.errSession': 'Сессия закончилась — войдите заново',
    'account.errInvoice': 'Не удалось создать счёт. Попробуйте ещё раз или напишите нам.',
    'account.errSubLoad': 'Не удалось проверить подписку. Обновите страницу или напишите нам.',
    'account.msgWait': 'Минуту…',
    'account.msgSending': 'Отправляю…',
    'account.msgInvoice': 'Готовлю счёт…',
    'account.msgSignedUp': 'Аккаунт создан. Проверьте почту и перейдите по ссылке из письма — потом войдите здесь.',
    'account.msgSent': 'Письмо отправлено. Перейдите по ссылке из него, затем войдите.',

    'account.pwEmpty': 'от 8 символов, буквы и цифры',
    'account.pwShort': 'коротковат: нужно хотя бы 8 символов',
    'account.pwCommon': 'этот пароль есть в списках для подбора',
    'account.pwPlain': 'одни буквы или одни цифры — добавьте разного',
    'account.pw2': 'сойдёт',
    'account.pw3': 'хороший',
    'account.pw4': 'надёжный',

    'paid.title': 'AutoSwipe AI — оплата принята',
    'paid.h1': 'Оплата принята',
    'paid.text': 'Платёж отправлен в сеть. Доступ откроется, как только транзакцию подтвердят — обычно это занимает от одной до нескольких минут.',
    'paid.btnCheck': 'Проверить состояние подписки',
    'paid.btnTinder': 'Перейти в Tinder',
    'paid.next': 'Что дальше',
    'paid.s1': 'Дождитесь подтверждения сети — обновите страницу кабинета через пару минут.',
    'paid.s2': 'Откройте расширение: в строке «Подписка» появится дата, до которой оплачено.',
    'paid.s3': 'Фильтры внешности и телосложения в панели разблокируются.',
    'paid.support': 'Если через полчаса доступ не открылся — напишите на <a href="mailto:support@autoswipeai.com">support@autoswipeai.com</a>, приложив адрес кошелька, с которого платили.',

    'confirmed.title': 'AutoSwipe AI — почта подтверждена',
    'confirmed.okTitle': 'Почта подтверждена',
    'confirmed.okText': 'Аккаунт готов. Откройте расширение и войдите.',
    'confirmed.badTitle': 'Ссылка не сработала',
    'confirmed.badText': 'Скорее всего, она устарела. Запросите новое письмо в расширении.',
    'confirmed.cta': 'Перейти в Tinder',
    'confirmed.next': 'Что дальше',
    'confirmed.s1': 'Нажмите иконку расширения в панели Chrome.',
    'confirmed.s2': 'Введите ту же почту и пароль — теперь вход пройдёт.',
    'confirmed.s3': 'Нажмите «Старт».',
  },

  /* ============================= українська ============================= */

  uk: {
    'common.langLabel': 'Мова сайту',
    'common.download': 'Завантажити',
    'common.pay': 'Оплатити',
    'common.back': 'На головну',
    'common.home': 'Головна',
    'common.footAccount': 'Особистий кабінет',
    'common.footTerms': 'Умови використання',
    'common.footPrivacy': 'Конфіденційність',
    'common.footRefund': 'Повернення коштів',
    'common.copy': '© {year} AutoSwipe AI · не пов’язані з Tinder і Match Group',

    'index.title': 'AutoSwipe AI — розширення Chrome для Tinder',
    'index.desc': 'Розширення Chrome, яке саме гортає рекомендації Tinder за вашими умовами: вік, зріст, відстань, стоп-слова в описі та оцінка фотографій моделлю.',
    'index.navHow': 'Як працює',
    'index.navWhat': 'Можливості',
    'index.navPrice': 'Ціна',
    'index.navFaq': 'Запитання',

    'index.heroEyebrow': 'Розширення для браузера Chrome',
    'index.heroTitle': 'Tinder гортає<br>себе сам',
    'index.heroLead': 'Ви один раз задаєте умови — вік, зріст, відстань, стоп-слова. Далі розширення саме відкриває анкети, оцінює фотографії та ставить Like або Nope.',
    'index.btnDownloadFull': 'Завантажити розширення',
    'index.btnPayFull': 'Оплатити підписку',
    'index.heroNote': 'Безкоштовно · Chrome 116 і новіше · встановлення в один клік',
    'index.soon': 'Скоро в Chrome Web Store',
    'index.soonNote': 'Розширення проходить перевірку в Chrome Web Store. Кабінет і оплата вже працюють.',

    'index.mockScore': 'Оцінка моделі 8,4 / 10',
    'index.mockName': 'Анна, 26',
    'index.mockMeta': '168 см · 4 км від вас · 5 фото',
    'index.mockAge': 'Вік',
    'index.mockHeight': 'Зріст',
    'index.mockHeightVal': '160 – 180 см',
    'index.mockDistance': 'Відстань',
    'index.mockDistanceVal': 'до 15 км',
    'index.mockLooks': 'Зовнішність',
    'index.mockStart': 'Старт',
    'index.mockLog': '<i class="y">♥</i> Like — оцінка 8,4<br><i class="n">✕</i> Nope — стоп-слово «мережі»<br><i class="y">♥</i> Like — оцінка 7,1<br><i class="n">✕</i> Nope — 42 км, далеко',

    'index.howTitle': 'Три кроки — і далі саме',
    'index.howSub': 'Нічого налаштовувати в браузері не треба: панель відкривається просто поверх Tinder.',
    'index.step1Title': 'Встановіть',
    'index.step1Text': 'Натисніть «Завантажити розширення» і підтвердьте встановлення в Chrome. Займає пів хвилини.',
    'index.step2Title': 'Задайте умови',
    'index.step2Text': 'Вік, зріст, відстань, мінімум фотографій, стоп-слова в описі. Повзунки та галочки, писати нічого не треба.',
    'index.step3Title': 'Натисніть «Старт»',
    'index.step3Text': 'Розширення гортає стрічку саме. Хто підійшов і чому — видно в лозі панелі, лічильники свайпів поруч.',

    'index.whatTitle': 'Що входить',
    'index.whatSub': 'Фільтри за анкетою працюють одразу й безкоштовно. Оцінка за фотографіями відкривається підпискою.',
    'index.freeTitle': 'Безкоштовно, одразу після встановлення',
    'index.free1': 'Вік, зріст, відстань',
    'index.free2': 'Мінімум фотографій в анкеті',
    'index.free3': 'Стоп-слова в описі, зокрема регулярні вирази',
    'index.free4': 'Лише з позначкою Verified або нещодавно активні',
    'index.free5': 'Ліміт свайпів за сесію та частка відмов',
    'index.free6': 'Інтерфейс українською, русским и English',
    'index.proTitle': 'За підпискою <span class="badge">AI</span>',
    'index.pro1': '<b>Фільтр за зовнішністю</b> — оцінка моделі від 1 до 10 і відбір за діапазоном',
    'index.pro2': '<b>Фільтр за статурою</b> — зріст і вага за фотографіями, діапазон ІМТ',
    'index.pro3': 'Відбір за тим, що видно на знімку, а не лише за заповненими полями анкети',

    'index.priceTitle': 'Ціна',
    'index.priceSub': 'Оплата криптовалютою або карткою з конвертацією. Автопродовження немає — ви платите за обраний строк, і він не спишеться сам.',
    'index.planMonth': 'Місяць',
    'index.planMonthPer': 'за 1 місяць доступу',
    'index.planMonthBtn': 'Оплатити місяць',
    'index.planYear': 'Рік',
    'index.planYearPer': 'за 12 місяців доступу',
    'index.planYearBtn': 'Оплатити рік',
    'index.ribbon': 'Вигідніше',
    'index.save': 'економія {n}%',
    'index.priceFoot': 'Оплата відкривається в кабінеті: потрібен акаунт — той самий, з яким ви входите в розширенні.<br><a data-i18n-doc="refund" href="/refund-uk.html">Умови повернення</a>',

    'index.faqTitle': 'Часті запитання',
    'index.faqSub': 'Коротко про те, що запитують перед покупкою.',
    'index.q1': 'Чи потрібен акаунт?',
    'index.a1': 'Так. Розширення працює під акаунтом — він же пов’язує вас із підпискою. Реєстрація поштою та паролем, просто у вікні розширення або тут на сайті.',
    'index.q2': 'Куди йдуть мої фотографії та листування?',
    'index.a2': 'Листування не читається взагалі. Фотографії профілів зі стрічки надсилаються до зовнішньої моделі для оцінки статури та зовнішності — без цього фільтри за знімками працювати не можуть. Ваші власні дані Tinder нікуди не передаються.',
    'index.q3': 'Наскільки точна оцінка за фотографією?',
    'index.a3': 'Це прикидка. Ракурс, одяг і обробка зсувають її, а оцінка зовнішності до того ж відображає упередженість даних, на яких модель навчалася. Число буде стабільним, але вважати його об’єктивним не варто.',
    'index.q4': 'Як влаштована оплата і чи можна скасувати?',
    'index.a4': 'Ви купуєте доступ на строк: місяць або рік. Автосписання немає — з криптовалютою його технічно не існує, тож скасовувати нічого. Не продовжили — доступ просто закінчився в оплачену дату. Продовжили раніше строку — новий період додасться до залишку, нічого не згорає.',
    'index.q5': 'Чи дозволено це правилами Tinder?',
    'index.a5': 'Ні. Правила Tinder забороняють автоматизацію дій у застосунку, і акаунт за це можуть обмежити або заблокувати. Розширення робить паузи між свайпами й тримає частку відмов, щоб поведінка не виглядала машинною, але гарантій це не дає. Рішення і ризик — ваші.',

    'index.bandTitle': 'Готові спробувати?',
    'index.bandSub': 'Встановлення безкоштовне. Підписка потрібна лише для оцінки за фотографіями.',

    'account.title': 'AutoSwipe AI — підписка',
    'account.payTitle': 'Оплата підписки',
    'account.payText': 'Відкриваю форму оплати…',
    'account.backToTinder': 'Повернутися в Tinder',
    'account.flow1': '1. Вхід',
    'account.flow2': '2. Оплата',
    'account.signInTitle': 'Вхід в акаунт',
    'account.signUpTitle': 'Реєстрація',
    'account.tabIn': 'Вхід',
    'account.tabUp': 'Реєстрація',
    'account.leadIn': 'Та сама пошта й пароль, що і в розширенні.',
    'account.leadUp': 'Цією ж поштою та паролем ви входитимете в розширенні.',
    'account.email': 'Пошта',
    'account.password': 'Пароль',
    'account.password2': 'Пароль ще раз',
    'account.submitIn': 'Увійти',
    'account.submitUp': 'Зареєструватися',
    'account.resend': 'Надіслати лист ще раз',
    'account.openMail': 'Відкрити {name}',
    'account.subTitle': 'Підписка',
    'account.rowAccount': 'Акаунт',
    'account.rowStatus': 'Стан',
    'account.rowUntil': 'Оплачена до',
    'account.pickTitle': 'Оберіть строк',
    'account.pickHint': 'Натисніть — відкриється форма оплати.',
    'account.payMonth': 'Оплатити місяць — {price}',
    'account.payYear': 'Оплатити рік — {price}',
    'account.saveYear': 'річна вигідніша на {n}%',
    'account.payNote': 'Криптовалютою або карткою з конвертацією. Автосписання немає — строк продовжуєте самі, новий період додається до оплаченого.',
    'account.signOut': 'Вийти',
    'account.whatTitle': 'Що відкриває підписка',
    'account.what1': '<b>Фільтр за зовнішністю</b> — відбір за оцінкою моделі 1–10, а не за анкетними полями.',
    'account.what2': '<b>Фільтр за статурою</b> — діапазон ІМТ за фотографіями.',
    'account.what3': 'Решта фільтрів — вік, зріст, відстань, стоп-слова — працюють без підписки.',
    'account.linkTerms': 'Умови',
    'account.linkRefund': 'Повернення',
    'account.linkPrivacy': 'Конфіденційність',

    'account.stActive': 'активна',
    'account.stTrialing': 'пробний період',
    'account.stPastDue': 'платіж не пройшов',
    'account.stPaused': 'призупинена',
    'account.stCanceled': 'скасована',
    'account.stNone': 'немає',

    'account.errEmpty': 'Введіть пошту й пароль',
    'account.errInvalid': 'Невірна пошта або пароль',
    'account.errNotConfirmed': 'Пошту не підтверджено — перейдіть за посиланням із листа',
    'account.errWeak': 'Пароль коротший за 6 символів',
    'account.errExists': 'Така пошта вже зареєстрована',
    'account.errValidation': 'Перевірте введені дані',
    'account.errRate': 'Занадто часто — зачекайте хвилину',
    'account.errMismatch': 'Паролі не збігаються',
    'account.errSimple': 'Пароль надто простий — його підберуть',
    'account.errTaken': 'Така пошта вже зареєстрована — увійдіть або відновіть пароль',
    'account.errSession': 'Сесія закінчилася — увійдіть заново',
    'account.errInvoice': 'Не вдалося створити рахунок. Спробуйте ще раз або напишіть нам.',
    'account.errSubLoad': 'Не вдалося перевірити підписку. Оновіть сторінку або напишіть нам.',
    'account.msgWait': 'Хвилинку…',
    'account.msgSending': 'Надсилаю…',
    'account.msgInvoice': 'Готую рахунок…',
    'account.msgSignedUp': 'Акаунт створено. Перевірте пошту й перейдіть за посиланням із листа — потім увійдіть тут.',
    'account.msgSent': 'Лист надіслано. Перейдіть за посиланням із нього, потім увійдіть.',

    'account.pwEmpty': 'від 8 символів, літери й цифри',
    'account.pwShort': 'закороткий: потрібно щонайменше 8 символів',
    'account.pwCommon': 'цей пароль є в списках для підбору',
    'account.pwPlain': 'самі літери або самі цифри — додайте різного',
    'account.pw2': 'згодиться',
    'account.pw3': 'хороший',
    'account.pw4': 'надійний',

    'paid.title': 'AutoSwipe AI — оплату прийнято',
    'paid.h1': 'Оплату прийнято',
    'paid.text': 'Платіж надіслано в мережу. Доступ відкриється, щойно транзакцію підтвердять — зазвичай це займає від однієї до кількох хвилин.',
    'paid.btnCheck': 'Перевірити стан підписки',
    'paid.btnTinder': 'Перейти в Tinder',
    'paid.next': 'Що далі',
    'paid.s1': 'Дочекайтеся підтвердження мережі — оновіть сторінку кабінету за пару хвилин.',
    'paid.s2': 'Відкрийте розширення: у рядку «Підписка» з’явиться дата, до якої оплачено.',
    'paid.s3': 'Фільтри зовнішності та статури в панелі розблокуються.',
    'paid.support': 'Якщо за пів години доступ не відкрився — напишіть на <a href="mailto:support@autoswipeai.com">support@autoswipeai.com</a>, додавши адресу гаманця, з якого платили.',

    'confirmed.title': 'AutoSwipe AI — пошту підтверджено',
    'confirmed.okTitle': 'Пошту підтверджено',
    'confirmed.okText': 'Акаунт готовий. Відкрийте розширення та увійдіть.',
    'confirmed.badTitle': 'Посилання не спрацювало',
    'confirmed.badText': 'Найімовірніше, воно застаріло. Запросіть новий лист у розширенні.',
    'confirmed.cta': 'Перейти в Tinder',
    'confirmed.next': 'Що далі',
    'confirmed.s1': 'Натисніть іконку розширення на панелі Chrome.',
    'confirmed.s2': 'Введіть ту саму пошту й пароль — тепер вхід пройде.',
    'confirmed.s3': 'Натисніть «Старт».',
  },

  /* ============================== English ============================== */

  en: {
    'common.langLabel': 'Site language',
    'common.download': 'Download',
    'common.pay': 'Subscribe',
    'common.back': 'Home',
    'common.home': 'Home',
    'common.footAccount': 'Account',
    'common.footTerms': 'Terms of use',
    'common.footPrivacy': 'Privacy',
    'common.footRefund': 'Refunds',
    'common.copy': '© {year} AutoSwipe AI · not affiliated with Tinder or Match Group',

    'index.title': 'AutoSwipe AI — Chrome extension for Tinder',
    'index.desc': 'A Chrome extension that swipes through Tinder recommendations for you: age, height, distance, stop-words in the bio and photo scoring by a vision model.',
    'index.navHow': 'How it works',
    'index.navWhat': 'Features',
    'index.navPrice': 'Price',
    'index.navFaq': 'FAQ',

    'index.heroEyebrow': 'Extension for the Chrome browser',
    'index.heroTitle': 'Tinder swipes<br>itself',
    'index.heroLead': 'You set the rules once — age, height, distance, stop-words. From there the extension opens profiles on its own, scores the photos and hits Like or Nope.',
    'index.btnDownloadFull': 'Download extension',
    'index.btnPayFull': 'Get a subscription',
    'index.heroNote': 'Free · Chrome 116 or newer · installs in one click',
    'index.soon': 'Coming to the Chrome Web Store',
    'index.soonNote': 'The extension is under review in the Chrome Web Store. The account and payment already work.',

    'index.mockScore': 'Model score 8.4 / 10',
    'index.mockName': 'Anna, 26',
    'index.mockMeta': '168 cm · 4 km away · 5 photos',
    'index.mockAge': 'Age',
    'index.mockHeight': 'Height',
    'index.mockHeightVal': '160 – 180 cm',
    'index.mockDistance': 'Distance',
    'index.mockDistanceVal': 'up to 15 km',
    'index.mockLooks': 'Looks',
    'index.mockStart': 'Start',
    'index.mockLog': '<i class="y">♥</i> Like — score 8.4<br><i class="n">✕</i> Nope — stop-word “networks”<br><i class="y">♥</i> Like — score 7.1<br><i class="n">✕</i> Nope — 42 km, too far',

    'index.howTitle': 'Three steps, then it runs itself',
    'index.howSub': 'Nothing to configure in the browser: the panel opens right on top of Tinder.',
    'index.step1Title': 'Install it',
    'index.step1Text': 'Press “Download extension” and confirm the install in Chrome. Takes half a minute.',
    'index.step2Title': 'Set your rules',
    'index.step2Text': 'Age, height, distance, minimum number of photos, stop-words in the bio. Sliders and checkboxes — nothing to type.',
    'index.step3Title': 'Press Start',
    'index.step3Text': 'The extension swipes the feed on its own. Who matched and why is right in the panel log, with swipe counters next to it.',

    'index.whatTitle': 'What you get',
    'index.whatSub': 'Profile-field filters work straight away and for free. Photo scoring comes with the subscription.',
    'index.freeTitle': 'Free, right after install',
    'index.free1': 'Age, height, distance',
    'index.free2': 'Minimum number of photos in a profile',
    'index.free3': 'Stop-words in the bio, regular expressions included',
    'index.free4': 'Verified badge only, or recently active only',
    'index.free5': 'Swipe limit per session and share of passes',
    'index.free6': 'Interface in English, русский and українською',
    'index.proTitle': 'With a subscription <span class="badge">AI</span>',
    'index.pro1': '<b>Looks filter</b> — a model score from 1 to 10 and a range to keep',
    'index.pro2': '<b>Body filter</b> — height and weight from the photos, a BMI range',
    'index.pro3': 'Filtering by what the photo actually shows, not only by the fields someone bothered to fill in',

    'index.priceTitle': 'Price',
    'index.priceSub': 'Pay with crypto or by card with conversion. There is no auto-renewal — you pay for the term you picked, and nothing is charged on its own.',
    'index.planMonth': 'Month',
    'index.planMonthPer': 'for 1 month of access',
    'index.planMonthBtn': 'Pay for a month',
    'index.planYear': 'Year',
    'index.planYearPer': 'for 12 months of access',
    'index.planYearBtn': 'Pay for a year',
    'index.ribbon': 'Better value',
    'index.save': 'saves {n}%',
    'index.priceFoot': 'Payment opens in your account: you need one — the same you sign in with in the extension.<br><a data-i18n-doc="refund" href="/refund-en.html">Refund terms</a>',

    'index.faqTitle': 'Frequently asked',
    'index.faqSub': 'The short answers to what people ask before buying.',
    'index.q1': 'Do I need an account?',
    'index.a1': 'Yes. The extension runs under an account — the same one that ties you to the subscription. Sign up with an email and password, either in the extension window or here on the site.',
    'index.q2': 'Where do my photos and chats go?',
    'index.a2': 'Chats are never read. Profile photos from the feed are sent to an external model to score body type and looks — the photo filters cannot work without that. Your own Tinder data is not sent anywhere.',
    'index.q3': 'How accurate is the photo score?',
    'index.a3': 'It is an estimate. Angle, clothing and editing shift it, and the looks score also carries the bias of the data the model was trained on. The number will be consistent, but do not treat it as objective.',
    'index.q4': 'How does payment work and can I cancel?',
    'index.a4': 'You buy access for a term: a month or a year. There is no recurring charge — with crypto it technically does not exist, so there is nothing to cancel. Did not renew? Access simply ends on the date you paid through. Renewed early? The new term is added to what is left, nothing is lost.',
    'index.q5': 'Is this allowed by Tinder’s rules?',
    'index.a5': 'No. Tinder’s rules prohibit automating actions in the app, and your account can be limited or banned for it. The extension pauses between swipes and keeps a share of passes so the behaviour does not look machine-like, but that is not a guarantee. The decision and the risk are yours.',

    'index.bandTitle': 'Ready to try it?',
    'index.bandSub': 'Installing is free. The subscription is only for the photo-based scoring.',

    'account.title': 'AutoSwipe AI — subscription',
    'account.payTitle': 'Subscription payment',
    'account.payText': 'Opening the payment form…',
    'account.backToTinder': 'Back to Tinder',
    'account.flow1': '1. Sign in',
    'account.flow2': '2. Payment',
    'account.signInTitle': 'Sign in',
    'account.signUpTitle': 'Create an account',
    'account.tabIn': 'Sign in',
    'account.tabUp': 'Sign up',
    'account.leadIn': 'The same email and password as in the extension.',
    'account.leadUp': 'You will sign in to the extension with this email and password.',
    'account.email': 'Email',
    'account.password': 'Password',
    'account.password2': 'Password again',
    'account.submitIn': 'Sign in',
    'account.submitUp': 'Create account',
    'account.resend': 'Send the email again',
    'account.openMail': 'Open {name}',
    'account.subTitle': 'Subscription',
    'account.rowAccount': 'Account',
    'account.rowStatus': 'Status',
    'account.rowUntil': 'Paid through',
    'account.pickTitle': 'Choose a term',
    'account.pickHint': 'Press one — the payment form opens.',
    'account.payMonth': 'Pay for a month — {price}',
    'account.payYear': 'Pay for a year — {price}',
    'account.saveYear': 'the yearly one saves {n}%',
    'account.payNote': 'Crypto or card with conversion. No recurring charge — you renew yourself, and the new term is added to what you already paid for.',
    'account.signOut': 'Sign out',
    'account.whatTitle': 'What the subscription unlocks',
    'account.what1': '<b>Looks filter</b> — selection by a model score of 1–10 rather than by profile fields.',
    'account.what2': '<b>Body filter</b> — a BMI range read from the photos.',
    'account.what3': 'The other filters — age, height, distance, stop-words — work without a subscription.',
    'account.linkTerms': 'Terms',
    'account.linkRefund': 'Refunds',
    'account.linkPrivacy': 'Privacy',

    'account.stActive': 'active',
    'account.stTrialing': 'trial',
    'account.stPastDue': 'payment failed',
    'account.stPaused': 'paused',
    'account.stCanceled': 'canceled',
    'account.stNone': 'none',

    'account.errEmpty': 'Enter your email and password',
    'account.errInvalid': 'Wrong email or password',
    'account.errNotConfirmed': 'Email not confirmed — follow the link we sent you',
    'account.errWeak': 'Password is shorter than 6 characters',
    'account.errExists': 'That email is already registered',
    'account.errValidation': 'Check what you entered',
    'account.errRate': 'Too often — wait a minute',
    'account.errMismatch': 'The passwords do not match',
    'account.errSimple': 'That password is too simple — it will be guessed',
    'account.errTaken': 'That email is already registered — sign in or reset your password',
    'account.errSession': 'Your session ended — sign in again',
    'account.errInvoice': 'The invoice could not be created. Try again or write to us.',
    'account.errSubLoad': 'The subscription could not be checked. Reload the page or write to us.',
    'account.msgWait': 'One moment…',
    'account.msgSending': 'Sending…',
    'account.msgInvoice': 'Preparing the invoice…',
    'account.msgSignedUp': 'Account created. Check your email and follow the link — then sign in here.',
    'account.msgSent': 'Email sent. Follow the link in it, then sign in.',

    'account.pwEmpty': '8 characters or more, letters and digits',
    'account.pwShort': 'a bit short: 8 characters at least',
    'account.pwCommon': 'this password is in the lists used for guessing',
    'account.pwPlain': 'all letters or all digits — mix it up',
    'account.pw2': 'will do',
    'account.pw3': 'good',
    'account.pw4': 'strong',

    'paid.title': 'AutoSwipe AI — payment received',
    'paid.h1': 'Payment received',
    'paid.text': 'The payment has been sent to the network. Access opens as soon as the transaction is confirmed — usually one to a few minutes.',
    'paid.btnCheck': 'Check subscription status',
    'paid.btnTinder': 'Go to Tinder',
    'paid.next': 'What next',
    'paid.s1': 'Wait for the network to confirm — reload the account page in a couple of minutes.',
    'paid.s2': 'Open the extension: the “Subscription” row will show the date you are paid through.',
    'paid.s3': 'The looks and body filters in the panel unlock.',
    'paid.support': 'If access has not opened within half an hour, write to <a href="mailto:support@autoswipeai.com">support@autoswipeai.com</a> and include the wallet address you paid from.',

    'confirmed.title': 'AutoSwipe AI — email confirmed',
    'confirmed.okTitle': 'Email confirmed',
    'confirmed.okText': 'Your account is ready. Open the extension and sign in.',
    'confirmed.badTitle': 'That link did not work',
    'confirmed.badText': 'It has most likely expired. Request a new email from the extension.',
    'confirmed.cta': 'Go to Tinder',
    'confirmed.next': 'What next',
    'confirmed.s1': 'Click the extension icon in the Chrome toolbar.',
    'confirmed.s2': 'Enter the same email and password — sign-in will work now.',
    'confirmed.s3': 'Press Start.',
  },
};
